/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tree;


public class App {

    public static void main(String[] args) {
       Tree tree = new Tree();
        tree.insert(7);
        tree.insert(4);
        tree.insert(9);
        tree.insert(1);
        tree.insert(6);
        tree.insert(8);
        tree.insert(10);

        Tree tree2 = new Tree();
        tree2.insert(7);
        tree2.insert(4);
        tree2.insert(9);
        tree2.insert(1);
        tree2.insert(6);
        tree2.insert(8);
        tree2.insert(10);




//        tree.preOrder();
//        tree.inOrder();
//        tree.postOrder();
//        System.out.println("height");
//        System.out.println(tree.height());
//        System.out.println("minimum");
//        System.out.println(tree.min());
//        System.out.println(tree.minBS());
//        System.out.println("maximum");
//        System.out.println(tree.max());


     System.out.println(tree.equal(tree2));
     System.out.println(tree.equal(tree2));

    }
}
